[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
keyring_network = "3MxhjuscSykCxXaozceBAUySdp6qHieB7sTXdarYAXTp"

[programs.localnet]
keyring_network = "3MxhjuscSykCxXaozceBAUySdp6qHieB7sTXdarYAXTp"

[programs.mainnet]
keyring_network = "3MxhjuscSykCxXaozceBAUySdp6qHieB7sTXdarYAXTp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sahil/.config/solana/id.json"

[scripts]
test = "cargo test"
