[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
smart_contract_solana = "9tDMCGD9wDGE9ZEqGRteg9sR9kVEm7wxqdHZnHDdC3qw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"  # or "https://api.mainnet-beta.solana.com"
wallet = "./deploy-keypair.json"

[scripts]
test = "cargo test"
