[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
keyring_network = "hLkXzcA2hSRraTD57UhpihoBHQD6bKJiZ4oyU7v6QKx"

[programs.mainnet]
keyring_network = "hLkXzcA2hSRraTD57UhpihoBHQD6bKJiZ4oyU7v6QKx"

[programs.devnet]
keyring_network = "hLkXzcA2hSRraTD57UhpihoBHQD6bKJiZ4oyU7v6QKx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
