[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
seeds = false
skip-lint = false

[programs.devnet]
keyring_network = "GJ5ZVSwDmLDwokctrkdrxfYTRndDtPhso8p7imCGVvch"

[programs.localnet]
keyring_network = "GJ5ZVSwDmLDwokctrkdrxfYTRndDtPhso8p7imCGVvch"

[programs.mainnet]
keyring_network = "GJ5ZVSwDmLDwokctrkdrxfYTRndDtPhso8p7imCGVvch"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
