name: Upgrade Mainnet Program

on:
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    environment: mainnet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Squads Action
        uses: actions/checkout@v4
        with:
          repository: Squads-Protocol/squads-v4-program-upgrade
          ref: main
          path: squads-action

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build and Run Squads Action
        working-directory: squads-action
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"  # Increase memory limit
          NETWORK_URL: "https://solana-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}"
          MULTISIG_PDA: ${{ vars.MULTISIG_PDA }}
          MULTISIG_VAULT_INDEX: "0"
          PROGRAM_ID: ${{ vars.PROGRAM_ID }}
          BUFFER: ${{ vars.BUFFER_ADDRESS }}
          SPILL_ADDRESS: ${{ vars.SPILL_ADDRESS }}
          NAME: "Keyring Network Program Upgrade"
          EXECUTABLE_DATA: ${{ vars.EXECUTABLE_DATA }}
          KEYPAIR: ${{ secrets.DEPLOYER_KEYPAIR }}
          IDL_BUFFER: ""  # Optional, set if needed
        run: |
          npm install
          npm run build
          npm run dev
        shell: bash 