name: Upgrade Mainnet Program

on:
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    environment: mainnet

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Program Upgrade via Squads
        uses: Squads-Protocol/squads-v4-program-upgrade@beta
        with:
          network-url: "https://solana-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}"
          multisig-pda: ${{ vars.MULTISIG }}
          multisig-vault-index: "0"
          program-id: ${{ vars.PROGRAM_ID }}
          buffer: ${{ vars.BUFFER_ADDRESS }}
          spill-address: ${{ vars.SPILL_ADDRESS }}
          name: "Keyring Network Program Upgrade"
          executable-data: ${{ vars.EXECUTABLE_DATA }}
          keypair: ${{ secrets.DEPLOYER_KEYPAIR }} 